"""Stub for type checking with mypy"""
from typing import Any

from registrationserver.base_actor import BaseActor


class RedirectorActor(BaseActor):
    ILLEGAL_STATE: Any = ...
    ILLEGAL_WRONGTYPE: Any = ...
    ILLEGAL_WRONGFORMAT: Any = ...
    LOOP: Any = ...
    def receive(self) -> None: ...
    def receiveMessage(self, msg, sender: Any) -> None: ...
