"""Stub for type checking with mypy"""
from typing import Any

from thespian.actors import Actor  # type: ignore


class RedirectorActor(Actor):
    ILLEGAL_STATE: Any = ...
    ILLEGAL_WRONGTYPE: Any = ...
    ILLEGAL_WRONGFORMAT: Any = ...
    LOOP: Any = ...
    def receive(self) -> None: ...
    def receiveMessage(self, msg: Any, sender: Any) -> None: ...
