"""Stub for type checking with mypy."""
from typing import Any, Dict

from thespian.actors import Actor  # type: ignore


class DeviceBaseActor(Actor):
    ACCEPTED_COMMANDS: Any = ...
    setup_done: bool = ...
    reservation: dict
    def receiveMessage(self, msg: Any, sender: Any) -> None: ...
    def _setup(self, msg, sender: Any) -> None: ...
    def _kill(self, msg, sender: Any) -> None: ...
    def _reserve(self, msg, sender: Any) -> None: ...
    def __init__(self) -> None: ...
