from registrationserver2 import actor_system as actor_system
from registrationserver2.modules.device_base_actor import DeviceBaseActor as DeviceBaseActor
from registrationserver2.modules.messages import RETURN_MESSAGES as RETURN_MESSAGES
from thespian.actors import Actor, ActorAddress as ActorAddress
from typing import Any

class DeviceActorManager(Actor):
    ACCEPTED_MESSAGES: Any = ...
    actors: dict
    def receiveMessage(self, msg: Any, sender: Any) -> None: ...
    @staticmethod
    def __echo__(msg: dict) -> dict: ...
    def __create__(self, msg: dict) -> dict: ...
    def __kill__(self, msg: dict) -> dict: ...

DEVICE_ACTOR_MANAGER: ActorAddress
