from builtins import staticmethod as staticmethod
from registrationserver2 import theLogger as theLogger
from registrationserver2.modules.messages import RETURN_MESSAGES as RETURN_MESSAGES
from thespian.actors import Actor
from typing import Any

class DeviceBaseActor(Actor):
    ACCEPTED_MESSAGES: Any = ...
    setup_done: bool = ...
    reservation: dict
    def receiveMessage(self, msg: Any, sender: Any) -> None: ...
    @staticmethod
    def __echo__(msg: dict) -> dict: ...
    def __setup__(self, msg: dict) -> dict: ...
    def __kill__(self, msg: dict) -> dict: ...
    def __reserve__(self, msg: dict) -> dict: ...
    def __init__(self) -> None: ...
