"""Stub for type checking with mypy."""
from typing import Any

from thespian.actors import Actor  # type: ignore


class DeviceBaseActor(Actor):
    ACCEPTED_MESSAGES: Any = ...
    setup_done: bool = ...
    reservation: dict
    def receiveMessage(self, msg: Any, sender: Any) -> None: ...
    @staticmethod
    def __echo__(msg: dict) -> dict: ...
    def __setup__(self, msg: dict) -> dict: ...
    def __kill__(self, msg: dict) -> dict: ...
    def __reserve__(self, msg: dict) -> dict: ...
    def __init__(self) -> None: ...
