"""Stub for type checking with mypy."""
from typing import Any

from thespian.actors import Actor  # type: ignore


class DeviceBaseActor(Actor):
    ACCEPTED_MESSAGES: Any = ...
    setup_done: bool = ...
    reservation: dict
    def receiveMessage(self, msg: Any, sender: Any) -> None: ...
    @staticmethod
    def _echo(msg: dict) -> dict: ...
    def _setup(self, msg: dict) -> dict: ...
    def _kill(self, msg: dict) -> dict: ...
    def _reserve(self, msg: dict) -> dict: ...
    def __init__(self) -> None: ...
