"""Stub file for type checking with Mypy"""
from typing import Any

from registrationserver.modules.device_actor import DeviceBaseActor


class MqttActor(DeviceBaseActor):
    reserve_req_msg: Any = ...
    free_req_msg: Any = ...
    is_id: Any
    instr_id: Any
    actor_name: Any
    actor_adr: Any
    allowed_sys_topics: Any = ...
    pub_req_msg: Any = ...
    sub_req_msg: Any = ...
    def __init__(self) -> None: ...
    def _send(self, msg, sender: Any) -> Any: ...
    def _reserve(self, msg, sender: Any): ...
    def _free(self, msg, sender: Any): ...
    def _kill(self, msg, sender: Any): ...
    def _property_store(self): ...
    def _prepare(self): ...
    def _mqtt_message(self, msg: Any) -> None: ...
