"""Stub file for type checking with Mypy"""
from typing import Any, Optional

from zeroconf import ServiceListener, Zeroconf


class MdnsListener(ServiceListener):
    def add_service(self, zc: Zeroconf, type_: str, name: str) -> None: ...
    def remove_service(self, zc: Zeroconf, type_: str, name: str) -> None: ...
    def update_service(self, zc: Zeroconf, type_: str, name: str) -> None: ...
    @staticmethod
    def convert_properties(info: Optional[Any] = ..., name: str = ...): ...
    def __init__(self, _type: Any) -> None: ...
