"""Stub file for type checking with Mypy"""
from typing import Any, Dict

from registrationserver2.modules.device_base_actor import DeviceBaseActor


class Rfc2217Actor(DeviceBaseActor):
    def _send(self, msg: dict, sender: Any) -> Any: ...
    def _reserve(self, msg: dict, sender: Any): ...
    def _free(self, msg: dict, sender: Any) -> None: ...
    def _kill(self, msg: Dict[Any, Any], sender: Any) -> None: ...

def _test() -> None: ...
