from registrationserver2 import theLogger as theLogger
from registrationserver2.modules.device_base_actor import DeviceBaseActor as DeviceBaseActor
from registrationserver2.modules.messages import RETURN_MESSAGES as RETURN_MESSAGES
from typing import Any

class Rfc2217Actor(DeviceBaseActor):
    def __send__(self, msg: dict) -> Any: ...
    def __reserve__(self, msg: Any): ...
    def __free__(self, msg: Any) -> None: ...
    def __kill__(self, msg: dict) -> Any: ...

def __test__() -> None: ...
