"""Stub file for type checking with Mypy"""
from typing import Any

from registrationserver2.modules.device_base_actor import DeviceBaseActor


class Rfc2217Actor(DeviceBaseActor):
    def _send(self, msg: dict) -> Any: ...
    def _reserve(self, msg: Any): ...
    def _free(self, msg: Any) -> None: ...
    def _kill(self, msg: dict) -> Any: ...

def _test() -> None: ...
