@startuml
autonumber "<b>[0]"
participant "SARAD App" as app
participant "Redirector Actor" as redirector
participant "Device Actor\nusb_actor" as device_actor
participant "Cluster Actor" as cluster
participant "Device File" as file

activate app
app -> redirector: close socket
destroy app
activate redirector
note over redirector: close listening socket
redirector -> device_actor: ChildActorExited
destroy redirector
device_actor -> file: write
device_actor -> cluster: FreeInstrMsg
deactivate device_actor
@enduml
