@startuml
control "SARAD app" as app
box "Registration Server 2"
        entity "REST API" as api
        entity "device actor" as deviceactor
        database "device files" as files
end box

group list
        app -> api: HTTP request GET /list/
        api -> files: read
        api -> app: HTTP response
end
group reservation
        app -> api: HTTP request GET /list/<id>/reserve?who="..."
        api -> deviceactor: RESERVE message
        deviceactor -> deviceactor: manage the Reserve request
        deviceactor -> files: write Reservation section
        deviceactor -> api: RETURN
        api -> files: read
        api -> app: HTTP response
end
group free
        app -> api: HTTP request GET /list/<id>/free
        api -> deviceactor: FREE message
        deviceactor -> deviceactor: manage the Free request
        deviceactor -> files: write Free section\nremove Reservation section
        deviceactor -> api: RETURN
        api -> files: read
        api -> app: HTTP response
end
@enduml
