@startuml
box "Registration Server 2"
	      entity "device actor" as deviceactor
        entity "redirector actor" as redirector
end box
entity "SARAD app" as app

group detection
        deviceactor -> redirector: create actor
        deviceactor -> redirector: SetupMsg
        deviceactor -> redirector: SetDeviceStatusMsg
end
group data transfer
	      app -> redirector: send binary paket\n to listening server socket
        redirector -> deviceactor: TxBinaryMsg
        deviceactor -> redirector: RxBinaryMsg
end
group free
        deviceactor -> redirector: KillMsg
        deviceactor <- redirector: ChildActorExited
end
@enduml
