@startuml
autonumber "<b>[0]"
participant "Instrument" as instr
participant "Cluster Actor" as cluster
participant "Device Actor\nusb_actor" as device_actor
participant "Redirector Actor" as redirector
participant "Registrar Actor" as registrar

activate cluster
activate instr
instr -> cluster: invalid reply msg
destroy instr
note over cluster: check validity of reply in _send()
note over cluster: call _remove_actor()
cluster -> device_actor: ActorExitRequest()
activate device_actor
activate redirector
device_actor -> redirector: KillMsg
note over redirector: close listening socket
redirector -> device_actor: ChildActorExited
destroy redirector
device_actor -> registrar: UnsubscribeMsg
destroy device_actor
@enduml
