@startuml
box "Registration Server 2"
	      entity "device actor" as deviceactor
        entity "redirector actor" as redirector
        database "device files" as files
end box
entity "SARAD app" as app

group reservation
        deviceactor -> redirector: create actor
        deviceactor -> redirector: SETUP message
        deviceactor <- redirector: RETURN message
        deviceactor -> files: write Reservation section
end
group data transfer
	      app -> redirector: send binary paket\n to listening server socket
        redirector -> deviceactor: SEND message
        deviceactor -> redirector: forward response as RETURN message
end
group free
        deviceactor -> redirector: KILL message
        deviceactor <- redirector: RETURN message
        deviceactor -> files: write Free section\n remove Reservation section
end
@enduml
