@startuml
autonumber "<b>[0]"
participant "SARAD Instrument" as instr
participant "Win/Unix Listener" as listener
participant "Cluster Actor" as cluster
participant "Device Actor\nusb_actor" as device_actor
participant "Device File" as file

instr -> listener: detect USB device
listener -> cluster: tell CMD: ADD
activate cluster
cluster -> instr: identify instrument
cluster -> device_actor: create
activate device_actor
cluster -> device_actor: CMD: SETUP
device_actor -> file: create
device_actor -> cluster: RETURN: SETUP
deactivate device_actor
deactivate cluster
@enduml
