@startuml
actor "Service Employee" as user
entity "Device with Instrument Server" as is
box "RegistrationServer 2"
entity "MdnsListener" as listener
entity "device actor" as deviceactor
end box
user -> is : attach instrument to local network
is -> listener : sends mDNS over multicast
listener -> deviceactor : create device actor
listener -> deviceactor : SETUP message
listener <- deviceactor : RETURN message
is -> user : unattach from network
is -> listener : sends disconnect over mDNS
listener -> deviceactor : KILL message
listener <- deviceactor : RETURN message
@enduml
