@startuml
box "Registration Server 2"
	      entity "REST API" as api
	      entity "device actor" as deviceactor
        entity "redirector actor" as redirector
        entity "Win USB listener" as listener
end box
entity "SARAD Instrument" as is
entity "SARAD app" as app

group setup
        is -> listener: detect
        listener -> deviceactor: create actor
        listener -> deviceactor: SetupMsg
        listener -> deviceactor: SetDeviceStatusMsg
end
group reservation
	      api -> deviceactor: ReserveDeviceMsg
        deviceactor -> redirector: create actor
        deviceactor -> redirector: SetupMsg
end
group data transfer
	      app -> redirector: send binary paket\n to listening server socket
        redirector -> deviceactor: TxBinaryMsg
        deviceactor -> is: send binary paket\n to listening server socket
        is -> deviceactor: send binary response from instrument
        deviceactor -> redirector: RxBinaryMsg
end
group free
	      api -> deviceactor: FreeDeviceMsg
        deviceactor -> redirector: KillMsg
end
@enduml
