@startuml
autonumber "<b>[0]"
participant "SARAD App" as app
participant "REST API" as api
participant "Device Actor\nusb_actor" as device_actor
participant "Redirector Actor" as redirector
participant "Device File" as file

app -> api: GET list
activate api
        api -> file: read
        api -> app: return list
deactivate api
app -> api: GET reserve
activate api
        api -> file: get_state_from_file()
        api -> device_actor: ask RESERVE
        activate device_actor
                device_actor -> redirector: create
                activate redirector
                device_actor -> redirector: CMD: SETUP
                note over redirector: listening socket to App
                redirector -> device_actor: RETURN: SETUP
                deactivate redirector
                device_actor -> device_actor: _return_with_socket()
                device_actor -> file: write
                device_actor -> api: RETURN: RESERVE
        deactivate device_actor
        api -> app: return outcome
deactivate api

@enduml
