@startuml
autonumber "<b>[0]"
participant "SARAD Instrument" as instr
participant "Win/Unix Listener" as listener
participant "Cluster Actor" as cluster
participant "Device Actor\nusb_actor" as device_actor

instr -> listener: detect USB device
listener -> cluster: tell InstrAddedMsg
activate cluster
cluster -> instr: identify instrument
cluster -> device_actor: create
activate device_actor
cluster -> device_actor: SetupMsg
cluster -> device_actor: SetDeviceStatusMsg
deactivate device_actor
deactivate cluster
@enduml
