@startuml
autonumber "<b>[0]"
participant "SARAD App" as app
participant "REST API" as api
participant "Device Actor\nusb_actor" as device_actor
participant "Redirector Actor" as redirector

app -> api: GET list
activate api
        api -> file: read
        api -> app: return list
deactivate api
app -> api: GET reserve
activate api
        api -> file: get_state_from_file()
        api -> device_actor: ReserveDeviceMsg
        activate device_actor
                device_actor -> redirector: create
                activate redirector
                device_actor -> redirector: SetupMsg
                note over redirector: listening socket to App
                redirector -> device_actor: SocketMsg
                deactivate redirector
                device_actor -> api: ReservationStatusMsg
        deactivate device_actor
        api -> app: return outcome
deactivate api

@enduml
