@startuml
box "RegistrationServer 2"
entity "Main Executable" as main
database "Configuration" as config
entity "mDNS" as mdns
entity "Rest API" as api
database "Instrument Server Connectors" as modules
end box
main -> config : Loads with config.py
main -> api : restapi.py
main -> mdns : mdnsListener.py
main -> modules : modules/*/
@enduml
