@startuml
box "RegistrationServer 2"
entity "Main Executable" as main
database "Configuration" as config
entity "mDNS" as mdns
entity "Rest API" as api
database "Instrument Server Connectors" as modules
end box
main -> config : read config.py
main -> api : start
main -> mdns : start
mdns -> modules : import required modules/*/
@enduml
