@startuml
box "Registration Server 2"
	      entity "REST API" as api
	      entity "device actor" as deviceactor
        entity "redirector actor" as redirector
        entity "listener" as listener
end box
entity "Instrument Server" as is

group setup
        is -> listener: mDNS multicast message
        listener -> deviceactor: create actor
        listener -> deviceactor: SetupMsg
        listener -> deviceactor: SetDeviceStatusMsg
end
group reservation
	      api -> deviceactor: ReserveDeviceMsg
        deviceactor -> is: Reserve request
        is -> deviceactor: Reserve response
        deviceactor -> redirector: create actor
        deviceactor -> redirector: SetupMsg
end
group data transfer
	      app -> redirector: send binary paket\n to listening server socket
        redirector -> deviceactor: TxBinaryMsg
        deviceactor -> is: send binary paket
        is -> deviceactor: receive binary response from instrument
        deviceactor -> redirector: RxBinaryMsg
end
group free
	      api -> deviceactor: FreeDeviceMsg
        deviceactor -> is: Free request
        is -> deviceactor: Free response
        deviceactor -> redirector: KillMsg
end
@enduml
