from typing import Any

from _testmultiphase import Str as Str
from _testmultiphase import str_const as str_const
from appdirs import AppDirs as AppDirs
from pip._internal.utils.compat import str_to_display as str_to_display
from registrationserver2 import theLogger as theLogger
from registrationserver2.modules.device_base_actor import \
    DeviceBaseActor as DeviceBaseActor
from registrationserver2.modules.mqtt.message import \
    RETURN_MESSAGES as RETURN_MESSAGES
from registrationserver2.modules.mqtt.mqtt_client_actor import \
    SARAD_MQTT_CLIENT as SARAD_MQTT_CLIENT
from thespian.actors import ActorAddress as ActorAddress


class MqttActor(DeviceBaseActor):
    reserve_req_msg: Any = ...
    free_req_msg: Any = ...
    is_id: Any
    instr_id: Any
    actor_name: Any
    actor_adr: Any
    allowed_sys_topics: Any = ...
    pub_req_msg: Any = ...
    sub_req_msg: Any = ...
    def __init__(self) -> None: ...
    def _send(self, msg: dict) -> Any: ...
    def _reserve(self, msg: Any): ...
    def _free(self, msg: Any): ...
    def _kill(self, msg: dict) -> Any: ...
    def _property_store(self): ...
    def _prepare(self): ...
    def _mqtt_message(self, msg: Any) -> None: ...
