from _testmultiphase import Str as Str, str_const as str_const
from appdirs import AppDirs as AppDirs
from pip._internal.utils.compat import str_to_display as str_to_display
from registrationserver2 import theLogger as theLogger
from registrationserver2.modules.device_base_actor import DeviceBaseActor as DeviceBaseActor
from registrationserver2.modules.mqtt.message import RETURN_MESSAGES as RETURN_MESSAGES
from registrationserver2.modules.mqtt.mqtt_client_actor import SARAD_MQTT_CLIENT as SARAD_MQTT_CLIENT
from thespian.actors import ActorAddress as ActorAddress
from typing import Any

class MqttActor(DeviceBaseActor):
    reserve_req_msg: Any = ...
    free_req_msg: Any = ...
    is_id: Any
    instr_id: Any
    actor_name: Any
    actor_adr: Any
    allowed_sys_topics: Any = ...
    pub_req_msg: Any = ...
    sub_req_msg: Any = ...
    def __init__(self) -> None: ...
    def __send__(self, msg: dict) -> Any: ...
    def __send_reserve__(self, msg: Any): ...
    def __send_free__(self, msg: Any): ...
    def __kill__(self, msg: dict) -> Any: ...
    def __property_store__(self): ...
    def __prepare__(self): ...
    def __mqtt_message__(self, msg: Any) -> None: ...
