"""Stub file for type checking with Mypy"""
from typing import Any

from thespian.actors import Actor, ActorAddress  # type: ignore


class SaradMqttClient(Actor):
    ACCEPTED_COMMANDS: Any = ...
    mqtt_topic: str
    mqtt_payload: str
    mqtt_qos: int = ...
    mqtt_broker: str
    mqtt_cid: str
    rc_conn: Any = ...
    def on_connect(
        self, client: Any, userdata: Any, flags: Any, result_code: Any
    ) -> None: ...
    rc_disc: Any = ...
    def on_disconnect(self, client: Any, userdata: Any, result_code: Any) -> None: ...
    rc_pub: int = ...
    def on_publish(self, client: Any, userdata: Any, mid: Any) -> None: ...
    rc_sub: int = ...
    def on_subscribe(
        self, client: Any, userdata: Any, mid: Any, grant_qos: Any
    ) -> None: ...
    rc_uns: int = ...
    def on_unsubscribe(self, client: Any, userdata: Any, mid: Any) -> None: ...
    topic_parts: Any = ...
    len: Any = ...
    def on_message(self, client: Any, userdata: Any, message: Any) -> None: ...
    def receiveMessage(self, msg: Any, sender: Any) -> None: ...
    mqttc: Any = ...
    wait_cnt: int = ...
    def _connect(self, msg: dict) -> dict: ...
    def _disconnect(self, msg: dict) -> dict: ...
    def _kill(self, msg: Any) -> None: ...
    def _publish(self, msg: dict) -> dict: ...
    def _subscribe(self, msg: dict) -> dict: ...
    def _unsubscribe(self, msg: dict) -> dict: ...
    def signal_handler(self, sig: Any, frame: Any) -> None: ...
    def __init__(self) -> None: ...

SARAD_MQTT_CLIENT: ActorAddress
