import socket
from registrationserver2 import actor_system as actor_system, theLogger as theLogger
from registrationserver2.modules import device_base_actor as device_base_actor
from registrationserver2.modules.device_actor_manager import DEVICE_ACTOR_MANAGER as DEVICE_ACTOR_MANAGER
from thespian.actors import Actor
from typing import Any

class SockInfo:
    address: str
    port: int
    def __init__(self, address: Any, port: Any) -> None: ...

class SocketClient:
    client_socket: socket
    client_address: SockInfo
    def __init__(self, client_socket: Any, client_address: Any) -> None: ...

class RedirectorActor(Actor):
    ILLEGAL_STATE: Any = ...
    ILLEGAL_WRONGTYPE: Any = ...
    ILLEGAL_WRONGFORMAT: Any = ...
    LOOP: Any = ...
    def receive(self) -> None: ...
    def receiveMessage(self, msg: Any, sender: Any) -> None: ...
