from registrationserver2 import FOLDER_AVAILABLE as FOLDER_AVAILABLE, FOLDER_HISTORY as FOLDER_HISTORY, FREE_KEYWORD as FREE_KEYWORD, PATH_AVAILABLE as PATH_AVAILABLE, PATH_HISTORY as PATH_HISTORY, RESERVE_KEYWORD as RESERVE_KEYWORD, theLogger as theLogger
from thespian.actors import Actor
from typing import Any, Optional

class RestApi(Actor):
    api: Any = ...
    class Dummy:
        @staticmethod
        def write(arg: Optional[Any] = ..., **kwargs: Any) -> None: ...
        @staticmethod
        def flush(arg: Optional[Any] = ..., **kwargs: Any) -> None: ...
    @staticmethod
    def get_list(): ...
    @staticmethod
    def get_device(did: Any): ...
    @staticmethod
    def get_history(): ...
    @staticmethod
    def get_device_old(did: Any): ...
    @staticmethod
    def reserve_device(did: Any): ...
    @staticmethod
    def free_device(did: Any): ...
    def run(self, host: Optional[Any] = ..., port: Optional[Any] = ..., debug: Optional[Any] = ..., load_dotenv: bool = ...) -> None: ...
