"""Stub file for type checking with Mypy"""
from typing import Any, Dict

from registrationserver.modules.device_actor import DeviceBaseActor


class Rfc2217Actor(DeviceBaseActor):
    def _send(self, msg, sender: Any) -> Any: ...
    def _reserve(self, msg, sender: Any): ...
    def _free(self, msg, sender: Any) -> None: ...
    def _kill(self, msg, sender: Any) -> None: ...

def _test() -> None: ...
