mdns_timeout = 3000
debug_level = "debug"
ip_version = "all"
port_range = [50000, 50500]
native_serial_ports = ["COM1"]
ignored_serial_ports = []
local_retry_interval = 86400  # in seconds
api_port = 8008
host = "::1"  # Localhost IPv6

[frontends]
rest = true
mqtt = false
mdns = false

[backends]
usb = true
mqtt = false
mdns = true
is1 = false

[mdns_frontend]
port_range = [5560, 5580]

[actor]
system_base = "multiprocUDPBase"
admin_port = 1901
process_startup_method = "spawn"

[mqtt]
mqtt_client_id = "Registration Server"
mqtt_broker = "sarad.de"
port = 8883
retry_interval = 5
tls_use_tls = true

[ismqtt]
is_id = "Instrument Server A"
description = "A longer text describing this Instrument Server"
place = "A text describing where the Instrument Controller running this Instrument Server is placed"
latitude = 51.0764194  # positive values for North, negative for South
longitude = 13.7383917  # positive values for East, negative for West
height = 102  # in meters
