debug_level = "debug"
# is_id = "aranea0003"
# description = "A longer text describing this Instrument Server"
# place = "A text describing where the Instrument Controller running this Instrument Server is placed"
# latitude = 51.0764194  # positive values for North, negative for South
# longitude = 13.7383917  # positive values for East, negative for West
# height = 102  # in meters

[frontends]
rest = true
mqtt = false
mdns = true
modbus_rtu = false

[backends]
usb = true
mqtt = false
mdns = false
is1 = true

[rest_frontend]
api_port = 8008
port_range = [50001, 50500]

[modbus_rtu_frontend]
slave_address = 1
port = "/dev/serial/by-id/usb-FTDI_Atil_UD-101i_USB__-__RS422_485-if00-port0"
baudrate = 9600
parity = "N"  # N: none, O: odd, E: even
device_id = "28tkhn4V.sarad-dacm.local"

[usb_backend]
poll_serial_ports = ["/dev/ttyS0"]
ignored_serial_ports = ["/dev/serial/by-id/usb-FTDI_Atil_UD-101i_USB__-__RS422_485-if00-port0"]
local_retry_interval = 10  # in seconds

[rs485_backend]
#"/dev/ttyUSB0" = [1]

[is1_backend]
registration_port = 50002
scan_interval = 60  # in seconds

[mdns_backend]
mdns_timeout = 3000
ip_version = "all"

[actor]
## Uncomment one of the following three base technologies for the Actor system
## A) Experimental multithreading base
# system_base = "multiprocQueueBase"
## B) UDP based messages
# system_base = "multiprocUDPBase"
# admin_port = 1029
## C) TCP based messages
system_base = "multiprocTCPBase"
admin_port = 1900
# convention_address = "127.0.0.1"

process_startup_method = "fork"
watchdog_interval = 5  # in minutes. 0 = inner watchdog switched off
watchdog_wait = 20  # in seconds
watchdog_check = false  # if true, each Actor has to re-register at the Registrar
outer_watchdog_interval = 60  # in seconds
outer_watchdog_trials = 0  # number of attempts to check Registrar

[mqtt]
group = "sarad-0001"
mqtt_broker = "sarad.de"
port = 8883
retry_interval = 5
tls_use_tls = true
