debug_level = "info"
# is_id = "Instrument Server A"
# description = "A longer text describing this Instrument Server"
# place = "A text describing where the Instrument Controller running this Instrument Server is placed"
# latitude = 51.0764194  # positive values for North, negative for South
# longitude = 13.7383917  # positive values for East, negative for West
# height = 102  # in meters

[frontends]
rest = true
mqtt = false
mdns = true
modbus_rtu = false

[backends]
usb = true
mqtt = false
mdns = true
is1 = false

[rest_frontend]
api_port = 8008
port_range = [50001, 50500]

[usb_backend]
poll_serial_ports = ["COM1"]
ignored_serial_ports = []
ignored_hwids = ["BTHENUM"]
# Serial Bluetooth device: "BTHENUM"
# FTDI USB-to-serial converters: "0403"
# Prolific and no-name USB-to-serial converters: "067B"
# QinHeng Electronics USB-to-serial converters: "1a86"
local_retry_interval = 10  # in seconds
set_realtime_clock = true  # set the RTC of instrument on every contact
use_utc = false  # UTC if true, local time if false

[is1_backend]
registration_port = 50002
scan_interval = 60  # in seconds

[mdns_backend]
mdns_timeout = 3000
ip_version = "all"
hosts = [[], []]  # [[host1, host2], [port1, port2]]
scan_interval = 60  # in seconds, 0 = scan only once during startup

[actor]
## Uncomment one of the following three base technologies for the Actor system
## A) Experimental multithreading base
system_base = "multiprocQueueBase"
## B) UDP based messages
# system_base = "multiprocUDPBase"
# admin_port = 1029
## C) TCP based messages
# system_base = "multiprocTCPBase"
# admin_port = 1900
# convention_address = "127.0.0.1"

process_startup_method = "spawn"
watchdog_interval = 2  # in seconds. 0 = inner watchdog switched off
watchdog_wait = 3  # in seconds. If IS1 backend is active and watchdog_check is
                   # True, this must be at least 35. In every other case it
                   # should be at least 10.
watchdog_check = true  # if true, each Actor has to re-register at the Registrar
outer_watchdog_interval = 60  # in seconds
outer_watchdog_trials = 1  # number of attempts to check Registrar

[mqtt]
group = "Registration Server"
mqtt_broker = "sarad.de"
port = 8883
keepalive = 60
qos = 0
retry_interval = 5
tls_use_tls = true

[mqtt_frontend]
reboot_after = 10  # Time in minutes after disconnect causing a reboot. 0 = never.
restart_instead_of_reboot = 1  # If set, the RegServer will be restarted instead
                               # of performing a reboot.