debug_level = "info"
# is_id = "Instrument Server A"
# description = "A longer text describing this Instrument Server"
# place = "A text describing where the Instrument Controller running this Instrument Server is placed"
# latitude = 51.0764194  # positive values for North, negative for South
# longitude = 13.7383917  # positive values for East, negative for West
# height = 102  # in meters

[frontends]
rest = true
mqtt = false
mdns = true

[backends]
usb = true
mqtt = false
mdns = true
is1 = false

[rest_frontend]
api_port = 8008
port_range = [50000, 50500]

[usb_backend]
native_serial_ports = ["COM1"]
ignored_serial_ports = []
local_retry_interval = 30  # in seconds

[is1_backend]
registration_port = 50002
scan_interval = 60  # in seconds

[mdns_backend]
mdns_timeout = 3000
ip_version = "all"

[actor]
system_base = "multiprocUDPBase"
admin_port = 1029
process_startup_method = "spawn"
watchdog_interval = 10  # in minutes
watchdog_wait = 20  # in seconds, has to be encreased for multiple native RS-232 ports
outer_watchdog_interval = 30  # in seconds
outer_watchdog_trials = 3  # number of attempts to check Registrar

[mqtt]
group = "Registration Server"
mqtt_broker = "sarad.de"
port = 8883
retry_interval = 5
tls_use_tls = true
