mdns_timeout = 3000
debug_level = "info"
ip_version = "all"
port_range = [50000, 50500]
native_serial_ports = ["COM1"]
ignored_serial_ports = []
local_retry_interval = 30  # in seconds
api_port = 8000
host = "::1"  # Localhost IPv6

[actor]
system_base = "multiprocTCPBase"
admin_port = 1901
process_startup_method = "spawn"

[mqtt]
mqtt_client_id = "SARAD_Subscriber"
mqtt_broker = "sarad.de"
port = 8883
retry_interval = 5
tls_use_tls = true
tls_ca_file = "~/.ssl/tls_cert_sarad.pem"
tls_cert_file = "~/.ssl/tls_cert_personal.crt"
tls_key_file = "~/.ssl/tls_key_personal.pem"

[ismqtt]
is_id = "Instrument Server A"
description = "A longer text describing this Instrument Server"
place = "A text describing where the Instrument Controller running this Instrument Server is placed"
latitude = 51.0764194  # positive values for North, negative for South
longitude = 13.7383917  # positive values for East, negative for West
height = 102  # in meters
