mdns_timeout = 3000
debug_level = "debug"
ip_version = "all"
port_range = [50000, 50500]
native_serial_ports = ["/dev/ttyS0"]
ignored_serial_ports = ["/dev/ttyS0"]
local_retry_interval = 3000  # in seconds
api_port = 8000
# host = "::1"  # Localhost IPv6
# host = "192.168.10.19"  # Michael@HomeVPN
host = "ap-strey.hq.sarad.de"  # Michael@Work
# host = "192.168.178.20"  # Michael@Home

[actor]
system_base = "multiprocTCPBase"
admin_port = 1901
process_startup_method = "fork"

[mqtt]
mqtt_client_id = "SARAD_Subscriber"
mqtt_broker = "85.214.243.156"
# mqtt_broker = "127.0.0.1"
port = 1883
retry_interval = 5
tls_use_tls = true
# tls_ca_file = "~/.ssl/SARAD/cert_sarad.pem"
# tls_cert_file = "~/.ssl/SARAD/personal_cert.crt"
# tls_key_file = "~/.ssl/SARAD/personal_key.pem"

[ismqtt]
is_id = "aranea0001"
description = "A longer text describing this Instrument Server"
place = "A text describing where the Instrument Controller running this Instrument Server is placed"
latitude = 51.0764194  # positive values for North, negative for South
longitude = 13.7383917  # positive values for East, negative for West
height = 102  # in meters
