mdns_timeout = 3000
debug_level = "debug"
ip_version = "all"
port_range = [50000, 50500]
native_serial_ports = []
ignored_serial_ports = []
local_retry_interval = 30  # in seconds
api_port = 8008
is_id = "aranea0003"

[frontends]
rest = true
mqtt = false
mdns = true

[backends]
usb = true
mqtt = false
mdns = true
is1 = true

[mdns_frontend]
port_range = [50000, 50500]

[is1_backend]
registration_port = 50002

[actor]
system_base = "multiprocUDPBase"
admin_port = 1901
process_startup_method = "fork"

[mqtt]
group = "sarad-regserv-0001"
mqtt_broker = "sarad.de"
port = 8883
retry_interval = 5
tls_use_tls = true

[ismqtt]
description = "A longer text describing this Instrument Server"
place = "A text describing where the Instrument Controller running this Instrument Server is placed"
latitude = 51.0764194  # positive values for North, negative for South
longitude = 13.7383917  # positive values for East, negative for West
height = 102  # in meters
